namespace Lykke.Service.IcoApi.Core.Domain.Campaign
{
    public enum CampaignInfoType
    {
        AmountPreSaleInvestedFiat,
        AmountPreSaleInvestedBtc,
        AmountPreSaleInvestedEth,
        AmountPreSaleInvestedUsd,
        AmountPreSaleInvestedSmarcToken,
        AmountPreSaleInvestedLogiToken,
        AmountCrowdSaleInvestedFiat,
        AmountCrowdSaleInvestedBtc,
        AmountCrowdSaleInvestedEth,
        AmountCrowdSaleInvestedUsd,
        AmountCrowdSaleInvestedSmarcToken,
        AmountCrowdSaleInvestedLogiToken,
        AddressPoolTotalSize,
        AddressPoolCurrentSize,
        AddressPoolLatestId,
        LastProcessedBlockBtc,
        LastProcessedBlockEth,
        LastProcessedBlockEthInfura,
        InvestorsRegistered,
        InvestorsConfirmed,
        InvestorsFilledIn,
        InvestorsPaidIn,
        InvestorsKycRequested,
        InvestorsKycPassed,
        LatestTransactions
    }
}
